services:
  - type: web
    name: luckylocker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn -w 2 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
